services:
  watcher:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: watcher
    image: watcher
    volumes:
      - ./services:/app/services
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

